# Generated by Django 4.1.5 on 2023-01-20 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MikoShutofo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculo',
            new_name='Datos',
        ),
    ]
