# Generated by Django 4.1.5 on 2023-01-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MikoShutofo', '0002_rename_vehiculo_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='contacto',
            field=models.CharField(max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
