# Generated by Django 4.1.5 on 2023-01-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MikoShutofo', '0003_datos_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='correo',
            field=models.CharField(max_length=15, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
