# Generated by Django 4.1.5 on 2023-01-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MikoShutofo', '0006_remove_datos_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='contacto',
            field=models.CharField(default='+569', max_length=15, verbose_name='Teléfono'),
        ),
    ]
