# Generated by Django 4.1.5 on 2023-01-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MikoShutofo', '0007_datos_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='contacto',
        ),
        migrations.AddField(
            model_name='datos',
            name='contato',
            field=models.CharField(default='+569', max_length=15, verbose_name='Número de contacto'),
        ),
        migrations.AddField(
            model_name='datos',
            name='correo',
            field=models.CharField(default='@', max_length=50, verbose_name='Correo Eletrónico'),
        ),
    ]
