# Generated by Django 4.1.5 on 2023-01-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MikoShutofo', '0008_remove_datos_contacto_datos_contato_datos_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='contato',
            field=models.CharField(default='569', max_length=15, verbose_name='Número de contacto'),
        ),
    ]
