# Generated by Django 4.1.5 on 2023-01-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MikoShutofo', '0009_alter_datos_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='contato',
            field=models.CharField(default='+569 ', max_length=15, verbose_name='Número de contacto'),
        ),
    ]
