# Generated by Django 4.1.5 on 2023-01-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MikoShutofo', '0011_alter_datos_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='correo',
            field=models.CharField(max_length=50, verbose_name='Correo Eletrónico'),
        ),
    ]
