# Generated by Django 4.1.5 on 2023-01-24 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MikoShutofo', '0012_alter_datos_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Tipo Producto')),
                ('nombreTipo', models.CharField(blank=True, max_length=30, verbose_name='Nombre Tipo Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre producto')),
                ('tamaño', models.CharField(blank=True, max_length=50, verbose_name='Tamaño en cm')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MikoShutofo.tipo', verbose_name='Categoria')),
            ],
        ),
    ]
